import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
          <footer class="bg-gray-800 text-white p-4 text-center mt-10">
            <p>&copy; 2024 Your Website Name. All rights reserved.</p>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
